/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;
import compiler.Lexer.Lexer;
import compiler.Lexer.Symbol;
import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class Compiler {

    public static void main(String[] args) {
        if (args.length >= 2 && "-lexer".equals(args[0])) {
            runLexer(args[1]);
            return;
        }
        System.out.println("Hello from the compiler !");
        System.out.println("Usage: gradle run --args=\"-lexer <input.lang>\"");
    }

    private static void runLexer(String filePath) {
        try (BufferedReader br = Files.newBufferedReader(Path.of(filePath))) {
            Lexer lexer = new Lexer(br);

            while (true) {
                Symbol s = lexer.getNextSymbol();
                System.out.println(s);
                if (s.getKind() == Symbol.Kind.EOF) break;
            }
        } catch (RuntimeException e) {
            System.err.println(e.getMessage());
            System.exit(2);
        } catch (IOException e) {
            System.err.println("Cannot read file: " + e.getMessage());
            System.exit(2);
        }
    }
}